config/routes.rb
Rails.application.routes.draw do
  root 'founds#index'

  get 'search', to: 'search#search'

  resources :founds, only: %i( show new  create )
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/found.rb
class Found < ApplicationRecord
  mount_uploader :picture, PictureUploader

  validates :name, presence: true
  validates :phone_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/founds_controller.rb
class FoundsController < ApplicationController

  def index
    @founds = Found.all
    @q = Found.ransack
  end

  def new
    @found = Found.new
  end

  def create
    @found = Found.new found_params
    if @found.save
      redirect_to @found, notice: '失物提交成功！'
    else
      render :new
    end
  end

  def show
    @found = Found.find params[:id]
  end

  private

    def found_params
      params.require(:found).permit(:name, :phone_number, :description, :picture)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @q = Found.ransack(params[:q])
    @results = @q.result
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/founds_helper.rb
module FoundsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/losts_helper.rb
module LostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/founds/index.html.erb
<style>
    .list-group-item {
      border: none;
      box-shadow: -1px 1px 2px rgba(255, 193, 7, 0.4);
      margin-bottom: 15px;
    }
  
    .form-control {
      border: 1px solid #f0d351;
      box-shadow: -1px 1px 2px #f8f9fa;
    }
  </style>
  
  <div class="container">
    <%= link_to "招领提交 +", new_found_path, class: 'btn btn-warning btn-block my-1' %>
      <%= search_form_for @q, url: search_path do |f| %>
        <div class="input-group">
          <%= f.search_field :description_cont, class: 'form-control', placeholder: "饭卡、手机、省份证、钱包..." %>
            <span class="input-group-btn">
              <%= f.submit '⏎', class: 'btn btn-warning' %>
            </span>
        </div>
        <% end %>
  
          <br>
  
          <div class="list-group">
            <% @founds.each do |f| %>
              <a href="<%= found_path(f) %>" class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-between">
                  <small class="mb-1">地点：第一教学楼</small>
                  <small>
                    <%= time_ago_in_words f.created_at %>
                  </small>
                </div>
                <div class="row">
                  <div class="col-4">
                    <%= image_tag(f.picture.url, size: '90x80') if f.picture.url %>
                  </div>
                  <div class="col-8">
                    <p class="mb-1">Donec id elit non mi porta gravida at eget metus.</p>
                  </div>
                </div>
                <small>
                  <%= f.name %>（
                    <%= f.phone_number %>）</small>
              </a>
  
              <% end %>
  
          </div>

app/views/founds/new.html.erb
<style>
    .form-control {
      border: none;
      box-shadow: -1px 1px 2px rgba(255, 193, 7, 0.4);
    }
</style>

<div class="container">
    
      <div class="row justify-content-center">
        <div class="col-9">
          <%= link_to root_path do %>
            <%= image_tag  "logo.jpg", size: "240x240" %>
          <% end %>
        </div>
      </div>
    
      <%= form_for( @found , remote: false) do |f| %>
        <div class="form-group row justify-content-center">
          <div class="col-9">
            <%= f.text_field :name, class: 'form-control', placeholder: '*姓名' %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <div class="col-9">
            <%= f.text_field :phone_number, class: 'form-control', placeholder: '*手机号' %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <div class="col-9">
            <%= f.text_area :description, class: 'form-control', placeholder: '描述' %>
          </div>
        </div>
    
        <div class="form-group row justify-content-center">
          <div class="col-9">
            <label class="custom-file">
              <%= f.file_field :picture, class: 'custom-file-input' %>
                <span class="custom-file-control">上传图片</span>
            </label>
          </div>
        </div>
    
        <div class="form_group row justify-content-center">
          <div class="col-9">
            <%= f.submit '失物提交', class: 'btn btn-warning btn-block' %>
          </div>
        </div>
        <% end %>
    </div>

app/views/founds/show.html.erb
<div class="jumbotron"></div>
<br>

<div class="container">
  <%= image_tag(@found.picture.url, class: 'card-img-top', size: '240x240') if @found.picture? %>
    <hr>
    <h3>姓名：
      <%= @found.name %>
    </h3>
    <h3>手机号：
      <%= @found.phone_number %>
    </h3>
    <h3>描述：
      <%= @found.description %>
    </h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostAndFound</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search/search.html.erb
<style>
    .list-group-item {
      border: none;
      box-shadow: -1px 1px 2px rgba(255, 193, 7, 0.4);
      margin-bottom: 15px;
    }
  
    .form-control {
      border: 1px solid #f0d351;
      box-shadow: -1px 1px 2px #f8f9fa;
    }
  </style>
  
  
  
  
  <div class="container">
    <%= link_to "招领提交 +", new_found_path, class: 'btn btn-warning btn-block my-1' %>
      <%= search_form_for @q, url: search_path do |f| %>
        <div class="input-group">
          <%= f.search_field :description_cont, class: 'form-control', placeholder: "饭卡、手机、省份证、钱包..." %>
            <span class="input-group-btn">
              <%= f.submit '⏎', class: 'btn btn-warning' %>
            </span>
        </div>
        <% end %>
  
          <br>
  
          <div class="list-group">
            <% @results.each do |r| %>
              <a href="<%= found_path(r) %>" class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-between">
                  <p class="mb-1">地点：第一教学楼</p>
                  <small>
                    <%= time_ago_in_words r.created_at %>
                  </small>
                </div>
                <div class="row">
                  <div class="col-4">
                    <%= image_tag(r.picture.url, size: '90x80') if r.picture.url %>
                  </div>
                  <div class="col-8">
                    <p class="mb-1">Donec id elit non mi porta gravida at eget metus.</p>
                  </div>
                </div>
                <small>
                  <%= r.name %>（
                    <%= r.phone_number %>）</small>
              </a>
  
              <% end %>
  
          </div>